server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yourdb
    username: root
    password: your-password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8

logging:
  level:
    org:
      springframework:
        web: DEBUG
        mail: DEBUG
